 //state de productos
 export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS'; 

 //state para el pedido de productos
export const SELECCIONAR_PRODUCTOS = 'SELECCIONAR_PRODUCTO';

export const CONFIRMAR_ORDENAR_PLATILLO = 'CONFIRMAR_ORDENAR_PLATILLO';


export const MOSTRAR_RESUMEN= 'MOSTRAR_RESUMEN';

export const  ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';

const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO';


